{{- if and .Values.adapter.enabled .Values.adapter.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "whizard.adapter.fullname" . }}
rules:
- apiGroups:
  - cluster.kubesphere.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.whizard.io
  resources:
  - tenants
  - service
  - storage
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secret
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}