# permissions for end users to edit queries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: whizard
    app.kubernetes.io/managed-by: kustomize
  name: query-editor-role
rules:
- apiGroups:
  - monitoring.whizard.io
  resources:
  - queries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.whizard.io
  resources:
  - queries/status
  verbs:
  - get
