
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosqueries/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosqueries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceives/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceives/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosstorages/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
