# permissions for end users to view rulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: whizard
    app.kubernetes.io/managed-by: kustomize
  name: ruler-viewer-role
rules:
- apiGroups:
  - monitoring.whizard.io
  resources:
  - rulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.whizard.io
  resources:
  - rulers/status
  verbs:
  - get
