# permissions for end users to edit service.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-editor-role
rules:
- apiGroups:
  - monitoring.paodin.io
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - service/status
  verbs:
  - get
