# permissions for end users to view service.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-viewer-role
rules:
- apiGroups:
  - monitoring.paodin.io
  resources:
  - service
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - service/status
  verbs:
  - get
