# permissions for end users to view services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: whizard
    app.kubernetes.io/managed-by: kustomize
  name: service-viewer-role
rules:
- apiGroups:
  - monitoring.whizard.io
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.whizard.io
  resources:
  - services/status
  verbs:
  - get
