
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: adapter-role
rules:
- apiGroups:
  - monitoring.whizard.io
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.kubesphere.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch