# permissions for end users to view thanos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanos-viewer-role
rules:
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanos/status
  verbs:
  - get
