# permissions for end users to edit thanosqueries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanosquery-editor-role
rules:
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosqueries/status
  verbs:
  - get
