# permissions for end users to edit thanosreceives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanosreceive-editor-role
rules:
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceives/status
  verbs:
  - get
