# permissions for end users to view thanosqueries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanosquery-viewer-role
rules:
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosqueries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosqueries/status
  verbs:
  - get
