# permissions for end users to view thanosreceives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanosreceive-viewer-role
rules:
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceives
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceives/status
  verbs:
  - get
