apiVersion: monitoring.paodin.io/v1alpha1
kind: Service
metadata:
  name: service-sample
  namespace: kubesphere-monitoring-system
spec:
  gateway: {}
  thanos: 
    query:
      stores:
      # - addresses:
      #   - prometheus-operated:10901
    receiveRouter: 
      replicationFactor: 2
