apiVersion: monitoring.whizard.io/v1alpha1
kind: Service
metadata:
  name: central
  namespace: kubesphere-monitoring-system
spec:
  router:
    replicationFactor: 2
  query:
    replicaLabelNames:
      - prometheus_replica
      - receive_replica
      - ruler_replica
