apiVersion: monitoring.paodin.io/v1alpha1
kind: Thanos
metadata:
  name: thanos-sample
  namespace: kubesphere-monitoring-system
spec:
  defaultFields:
    logLevel: info
  query:
    stores:
    # - addresses:
    #   - prometheus-operated:10901
  receive:
    router: 
      replicationFactor: 2
    ingestors:
    - name: soft-tenants
      replicas: 2
