apiVersion: monitoring.whizard.io/v1alpha1
kind: Router
metadata:
  labels:
    app.kubernetes.io/name: whizard
    app.kubernetes.io/managed-by: kustomize
    monitoring.whizard.io/service: kubesphere-monitoring-system.whizard
  name: router-sample
  namespace: kubesphere-monitoring-system
spec:
  # TODO(user): Add fields here
