{{- if .Values.ingester.enabled -}}
apiVersion: monitoring.whizard.io/v1alpha1
kind: Ingester
metadata:
  name: {{ include "whizard.ingester.crname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- if .Values.ingester.serviceReference }}
    "monitoring.whizard.io/service": {{ .Values.ingester.serviceReference.namespace }}.{{ .Values.ingester.serviceReference.name }}
    {{- else if .Values.service.enabled }}
    "monitoring.whizard.io/service": {{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}
    {{- end }}
    {{- if and .Values.storage.create .Values.storage.s3 }}
    "monitoring.whizard.io/storage": {{ include "whizard.namespace" . }}.{{ include "whizard.storage.crname" . }}
    {{- else }}
    "monitoring.whizard.io/storage": "local"
    {{- end }}
    {{- with .Values.ingester.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
{{- with .Values.ingester.additionalConfig }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with .Values.ingester.additionalConfigString }}
  {{- tpl . $ | nindent 2 }}
{{- end }}
{{- end }}
