{{- if .Values.gateway.enabled -}}
apiVersion: monitoring.whizard.io/v1alpha1
kind: Gateway
metadata:
  name: {{ include "whizard.gateway.crname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- if .Values.gateway.serviceReference }}
    "monitoring.whizard.io/service": "{{ .Values.gateway.serviceReference.namespace }}.{{ .Values.gateway.serviceReference.name }}"
    {{- else if .Values.service.enabled }}
    "monitoring.whizard.io/service": "{{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}"
    {{- end }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  nodePort: {{ .Values.gateway.nodePort }}
{{- with .Values.gateway.additionalConfig }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with .Values.gateway.additionalConfigString }}
  {{- tpl . $ | nindent 2 }}
{{- end }}
{{- end }}
