{{- if and .Values.controllerManager.enabled .Values.controllerManager.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whizard.fullname" . }}-config
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- include "whizard.labels" . | nindent 4 }}
data:   
  whizard.yaml: |
    {{- toYaml .Values.controllerManager.config.config | nindent 4 }}
{{ end }}