{{- if .Values.controllerManager.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whizard.manager.fullname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    app: {{ include "whizard.manager.fullname" . }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "whizard.manager.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "whizard.manager.fullname" . }}
    spec:
      serviceAccountName: {{ include "whizard.manager.serviceAccountName" . }}
      volumes:
      - name: whizard-config
        configMap:
          name: {{ include "whizard.fullname" . }}-config
          defaultMode: 420
      containers:
        - name: manager
          command:
          - /manager
          image: "{{ .Values.controllerManager.image.repository }}:{{ .Values.controllerManager.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
          - mountPath: /etc/whizard/
            name: whizard-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          {{- with .Values.controllerManager.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.controllerManager.adapter.enabled }}
        - name: adapter
          args:
          {{- if .Values.controllerManager.adapter.defaultServiceReference }}
          - --default-whizard-service={{ .Values.controllerManager.adapter.defaultServiceReference.namespace }}.{{ .Values.controllerManager.adapter.defaultServiceReference.name }}
          {{- else if .Values.service.enabled }}
          - --default-whizard-service={{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}
          {{- end }}
          - --kubesphere-adapter-enabled={{ .Values.controllerManager.adapter.kubesphereAdapter.enabled }}
          image: "{{ .Values.controllerManager.adapter.image.repository }}:{{ .Values.controllerManager.adapter.image.tag | default .Chart.AppVersion }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9091
      {{- end }}
      {{- with .Values.controllerManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
